---
name: Daily builds
on:
  schedule:
    - cron: 0 7 * * *
jobs:
  expo-v3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build image
        run: docker build . --tag nsollazzo/expo-dev
      - name: Authenticate docker
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u nsollazzo --password-stdin
      - name: Publish image
        run: docker push nsollazzo/expo-dev:latest
